"""
real_corridor.py — Loads real Indian Railways data for dataset-backed corridors:
- SBC-JTJ (Bengaluru City to Jolarpettai, 145.0 km)
- NDLS-CNB (New Delhi to Kanpur Central, 440.0 km)
- CSTM-PUNE (Mumbai CST to Pune Jn, 192.0 km)

Data source: https://github.com/datameet/railways
- stations.json: GeoJSON FeatureCollection with station code, name, coordinates
- trains.json: Route geometries and official route distances
- schedules.json: Flat array of ~417k per-station schedule rows

Station chainage is computed using cumulative Haversine great-circle distance
between consecutive corridor station coordinates, rescaled proportionally to match
the real ground-truth rail distance for each corridor.

Goods-train forecasts and TMS/SMMS/TDMS maintenance data remain synthetic
(generated by mock_data.py) as no public source exists for either.
"""

import json
import math
import os
import logging
from typing import List, Dict, Optional, Tuple
from backend.core.schemas import Station, TrainSchedule, TrainStop

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Corridor Configurations
# ---------------------------------------------------------------------------

CORRIDOR_CONFIGS = {
    "SBC-JTJ": {
        "codes": ["SBC", "BNC", "KJM", "WFD", "BWT", "KPN", "JTJ"],
        "total_km": 145.0,
        "shatabdi_pair": ("12028", "12027"),
        "operator": "Southern / South Western Railway",
        "target_trains_per_dir": 15,
    },
    "NDLS-CNB": {
        "codes": ["NDLS", "GZB", "ALJN", "TDL", "ETW", "CNB"],
        "total_km": 440.0,
        "shatabdi_pair": ("12034", "12033"),
        "operator": "Northern Railway / North Central Railway",
        "target_trains_per_dir": 15,
    },
    "CSTM-PUNE": {
        "codes": ["CSTM", "KYN", "KJT", "LNL", "PUNE"],
        "total_km": 192.0,
        "shatabdi_pair": ("12124", "12123"),
        "operator": "Central Railway",
        "target_trains_per_dir": 15,
    },
}

# Legacy constants for backward compatibility
CORRIDOR_CODES = CORRIDOR_CONFIGS["SBC-JTJ"]["codes"]
CORRIDOR_INDICES = {code: i for i, code in enumerate(CORRIDOR_CODES)}
REAL_CORRIDOR_TOTAL_KM = CORRIDOR_CONFIGS["SBC-JTJ"]["total_km"]

_DEFAULT_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "..", "railways")
DATA_DIR = os.environ.get("RAILWAYS_DATA_DIR", _DEFAULT_DATA_DIR)

# Type-specific average speeds (km/min) used for interpolating missing stops.
TYPE_SPEEDS = {
    "Vande Bharat": 1.5,   # ~90 km/h
    "Rajdhani": 1.4,       # ~84 km/h
    "Shatabdi": 1.3,       # ~78 km/h
    "Superfast": 1.1,      # ~66 km/h
    "Express": 0.9,        # ~54 km/h
    "Passenger": 0.6,      # ~36 km/h
}

# Default halt durations (minutes) at intermediate stations, by train type.
TYPE_HALT_MINS = {
    "Vande Bharat": 1,
    "Rajdhani": 1,
    "Shatabdi": 2,
    "Superfast": 2,
    "Express": 3,
    "Passenger": 5,
}

HORIZON_DAYS = 7
MINS_PER_DAY = 1440
TARGET_TRAINS_PER_DIR = 15

# ---------------------------------------------------------------------------
# Haversine distance
# ---------------------------------------------------------------------------

def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Computes the great-circle distance in km between two geographic points.
    """
    R = 6371.0  # Earth radius in km
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

# ---------------------------------------------------------------------------
# Train type classification
# ---------------------------------------------------------------------------

def _classify_train_type(train_name: str, train_number: str) -> str:
    """
    Infers train type from name/number using keyword heuristics.
    Priority order: Vande Bharat > Rajdhani > Shatabdi > Superfast > Passenger > Express.
    """
    name_upper = train_name.upper()

    if "VANDE BHARAT" in name_upper:
        return "Vande Bharat"
    if "RAJDHANI" in name_upper:
        return "Rajdhani"
    if "JAN SHATABDI" in name_upper or "JANSHATABDI" in name_upper:
        return "Superfast"
    if "SHATABDI" in name_upper:
        return "Shatabdi"
    if "DURONTO" in name_upper or "GARIB RATH" in name_upper:
        return "Superfast"
    if "SUPERFAST" in name_upper or " SF " in name_upper or name_upper.endswith(" SF") or " MAIL" in name_upper:
        return "Superfast"
    if "PASSENGER" in name_upper or "PASS." in name_upper:
        return "Passenger"
    if "INTERCITY" in name_upper or "EXPRESS" in name_upper or "EXP" in name_upper:
        return "Express"

    # Fallback by train number range (Indian Railways convention):
    try:
        num = int(train_number)
        if 50000 <= num <= 69999:
            return "Passenger"
        if 12000 <= num <= 12999 or 22000 <= num <= 22999:
            return "Superfast"
    except ValueError:
        pass

    return "Express"

# ---------------------------------------------------------------------------
# Time parsing
# ---------------------------------------------------------------------------

def _parse_time_to_mins(time_str: str, day: int = 1) -> Optional[int]:
    """
    Parses 'HH:MM:SS' into absolute minutes from Day 0 start.
    Returns None if the time string is 'None' or invalid.
    Day is 1-indexed in the source data; we convert to 0-indexed.
    """
    if not time_str or time_str == "None":
        return None
    try:
        parts = time_str.split(":")
        hours = int(parts[0])
        mins = int(parts[1])
        day_offset = (day - 1) * MINS_PER_DAY if day else 0
        return day_offset + hours * 60 + mins
    except (ValueError, IndexError):
        return None

# ---------------------------------------------------------------------------
# Load stations per corridor
# ---------------------------------------------------------------------------

def _load_corridor_stations(corridor_id: str = "SBC-JTJ") -> List[Station]:
    """
    Loads corridor stations from stations.json, computes cumulative
    Haversine distance from the origin station, and rescales proportionally to match the
    real ground-truth route distance for that corridor.
    """
    cfg = CORRIDOR_CONFIGS.get(corridor_id, CORRIDOR_CONFIGS["SBC-JTJ"])
    codes = cfg["codes"]
    total_km = cfg["total_km"]

    stations_path = os.path.join(DATA_DIR, "stations.json")
    with open(stations_path, "r", encoding="utf-8") as f:
        geojson = json.load(f)

    station_map: Dict[str, dict] = {}
    for feature in geojson["features"]:
        code = feature["properties"].get("code")
        if code in codes:
            geom = feature.get("geometry")
            coords = geom.get("coordinates") if geom else None
            if coords:
                station_map[code] = {
                    "code": code,
                    "name": feature["properties"]["name"],
                    "lon": coords[0],
                    "lat": coords[1],
                }

    missing = set(codes) - set(station_map.keys())
    if missing:
        raise ValueError(f"Missing corridor stations in data for {corridor_id}: {missing}")

    raw_haversine = [0.0]
    for i in range(1, len(codes)):
        prev = station_map[codes[i - 1]]
        curr = station_map[codes[i]]
        d = _haversine_km(prev["lat"], prev["lon"], curr["lat"], curr["lon"])
        raw_haversine.append(raw_haversine[-1] + d)

    scale_factor = total_km / raw_haversine[-1] if raw_haversine[-1] > 0 else 1.0

    stations: List[Station] = []
    for i, code in enumerate(codes):
        chainage = round(raw_haversine[i] * scale_factor, 1)
        stations.append(Station(
            id=code,
            code=code,
            name=station_map[code]["name"],
            chainage_km=chainage,
            latitude=station_map[code]["lat"],
            longitude=station_map[code]["lon"],
        ))

    logger.info(
        "Loaded %d corridor stations for %s (rescaled to %.1f km). Chainage range: 0 – %.1f km",
        len(stations), corridor_id, total_km, stations[-1].chainage_km,
    )
    return stations

# ---------------------------------------------------------------------------
# Load and filter schedules per corridor
# ---------------------------------------------------------------------------

def _load_corridor_schedules(corridor_id: str = "SBC-JTJ") -> List[dict]:
    """
    Loads schedules.json, filters to corridor station codes, groups by train_number,
    and enforces strict monotonicity along the corridor.
    """
    cfg = CORRIDOR_CONFIGS.get(corridor_id, CORRIDOR_CONFIGS["SBC-JTJ"])
    codes = cfg["codes"]
    indices = {code: i for i, code in enumerate(codes)}

    schedules_path = os.path.join(DATA_DIR, "schedules.json")
    with open(schedules_path, "r", encoding="utf-8") as f:
        all_rows = json.load(f)

    corridor_set = set(codes)
    trains: Dict[str, List[dict]] = {}
    for row in all_rows:
        if row.get("station_code") in corridor_set:
            tn = row["train_number"]
            trains.setdefault(tn, []).append(row)

    filtered_trains = []

    for tn, rows in trains.items():
        if len(rows) < 2:
            continue

        def sort_key(row):
            day = row.get("day") or 1
            if isinstance(day, str):
                day = int(day) if day.isdigit() else 1
            dep = _parse_time_to_mins(row.get("departure", "None"), day=1)
            arr = _parse_time_to_mins(row.get("arrival", "None"), day=1)
            t = dep if dep is not None else (arr if arr is not None else 0)
            return (day, t)

        sorted_rows = sorted(rows, key=sort_key)
        idx_seq = [indices[r["station_code"]] for r in sorted_rows]

        is_up = all(idx_seq[i] < idx_seq[i + 1] for i in range(len(idx_seq) - 1))
        is_dn = all(idx_seq[i] > idx_seq[i + 1] for i in range(len(idx_seq) - 1))

        if not (is_up or is_dn):
            continue

        direction = "Up" if is_up else "Down"
        span = max(idx_seq) - min(idx_seq)
        if span < 2:
            continue

        name = rows[0].get("train_name", "Unknown")
        t_type = _classify_train_type(name, tn)

        filtered_trains.append({
            "train_number": tn,
            "train_name": name,
            "type": t_type,
            "direction": direction,
            "rows": sorted_rows,
            "stops_count": len(idx_seq),
            "span": span,
        })

    logger.info(
        "Filtered %d strictly monotonic corridor trains for %s from %d raw candidates",
        len(filtered_trains), corridor_id, len(trains),
    )
    return filtered_trains

# ---------------------------------------------------------------------------
# Interpolation of missing stops
# ---------------------------------------------------------------------------

def _interpolate_stops(
    known_stops: List[TrainStop],
    all_stations: List[Station],
    chainage_map: Dict[str, float],
    direction: str,
    train_type: str,
) -> List[TrainStop]:
    """
    Given a partial set of known stops for a train, interpolates missing
    intermediate corridor stops proportionally using distance and type-specific
    average speed.
    """
    known_codes = {s.station_id for s in known_stops}

    ordered_stations = list(all_stations) if direction == "Up" else list(reversed(all_stations))
    known_map = {s.station_id: s for s in known_stops}

    ordered_codes = [s.code for s in ordered_stations]
    known_indices = [ordered_codes.index(code) for code in known_codes if code in ordered_codes]

    if len(known_indices) < 2:
        return known_stops

    first_idx = min(known_indices)
    last_idx = max(known_indices)

    result_stops: List[TrainStop] = []
    speed = TYPE_SPEEDS.get(train_type, 0.9)
    halt = TYPE_HALT_MINS.get(train_type, 3)

    for idx in range(first_idx, last_idx + 1):
        stn = ordered_stations[idx]
        if stn.code in known_map:
            result_stops.append(known_map[stn.code])
        else:
            prev_known = None
            next_known = None
            for pi in range(idx - 1, first_idx - 1, -1):
                if ordered_stations[pi].code in known_map:
                    prev_known = (pi, ordered_stations[pi])
                    break
            for ni in range(idx + 1, last_idx + 1):
                if ordered_stations[ni].code in known_map:
                    next_known = (ni, ordered_stations[ni])
                    break

            if prev_known and next_known:
                prev_idx, prev_stn = prev_known
                next_idx, next_stn = next_known
                prev_stop = known_map[prev_stn.code]
                next_stop = known_map[next_stn.code]

                total_dist = abs(chainage_map[next_stn.code] - chainage_map[prev_stn.code])
                if total_dist == 0:
                    total_dist = 1.0
                frac = abs(chainage_map[stn.code] - chainage_map[prev_stn.code]) / total_dist

                time_span = next_stop.arrival_mins - prev_stop.departure_mins
                interp_arrival = prev_stop.departure_mins + int(frac * time_span)
                interp_departure = interp_arrival + halt

                result_stops.append(TrainStop(
                    station_id=stn.code,
                    arrival_mins=interp_arrival,
                    departure_mins=interp_departure,
                ))

    return result_stops

# ---------------------------------------------------------------------------
# Build train schedules
# ---------------------------------------------------------------------------

def _build_train_schedule(
    train_number: str,
    train_name: str,
    train_type: str,
    rows: List[dict],
    stations: List[Station],
    chainage_map: Dict[str, float],
    direction: str,
) -> Optional[TrainSchedule]:
    known_stops: List[TrainStop] = []
    for row in rows:
        code = row["station_code"]
        if code not in chainage_map:
            continue

        day = row.get("day", 1) or 1
        arr = _parse_time_to_mins(row.get("arrival", "None"), day)
        dep = _parse_time_to_mins(row.get("departure", "None"), day)

        if arr is None and dep is not None:
            arr = dep
        elif dep is None and arr is not None:
            dep = arr
        elif arr is None and dep is None:
            continue

        known_stops.append(TrainStop(
            station_id=code,
            arrival_mins=arr,
            departure_mins=dep,
        ))

    if len(known_stops) < 2:
        return None

    known_stops.sort(key=lambda s: s.arrival_mins)
    all_stops = _interpolate_stops(known_stops, stations, chainage_map, direction, train_type)

    if len(all_stops) < 2:
        return None

    dir_suffix = "UP" if direction == "Up" else "DN"
    train_id = f"{train_number}_{dir_suffix}"

    return TrainSchedule(
        train_id=train_id,
        type=train_type,
        direction=direction,
        stops=all_stops,
    )

# ---------------------------------------------------------------------------
# Caching & Public API
# ---------------------------------------------------------------------------

_cached_stations: Dict[str, List[Station]] = {}
_cached_timetables: Dict[str, List[TrainSchedule]] = {}

def get_corridor_stations(corridor_id: str = "SBC-JTJ") -> List[Station]:
    """Returns the corridor stations with real names and rescaled chainage for the given corridor."""
    if corridor_id not in _cached_stations:
        _cached_stations[corridor_id] = _load_corridor_stations(corridor_id)
    return _cached_stations[corridor_id]

def get_real_timetables(corridor_id: str = "SBC-JTJ") -> List[TrainSchedule]:
    """Returns real train schedules across the planning horizon for the given corridor."""
    if corridor_id in _cached_timetables:
        return _cached_timetables[corridor_id]

    cfg = CORRIDOR_CONFIGS.get(corridor_id, CORRIDOR_CONFIGS["SBC-JTJ"])
    target_count = cfg.get("target_trains_per_dir", 15)
    shatabdi_pair = cfg.get("shatabdi_pair", ("12028", "12027"))

    stations = get_corridor_stations(corridor_id)
    chainage_map = {s.code: s.chainage_km for s in stations}

    candidate_trains = _load_corridor_schedules(corridor_id)
    up_candidates = [t for t in candidate_trains if t["direction"] == "Up"]
    dn_candidates = [t for t in candidate_trains if t["direction"] == "Down"]

    def _select_trains(candidates, direction):
        selected = []
        shatabdi_added = False
        sorted_cand = sorted(candidates, key=lambda x: (x["stops_count"], x["span"]), reverse=True)

        target_shatabdi = shatabdi_pair[0] if direction == "Up" else shatabdi_pair[1]
        for c in sorted_cand:
            if c["train_number"] == target_shatabdi and c["type"] in ("Shatabdi", "Superfast"):
                selected.append(c)
                shatabdi_added = True
                break

        if not shatabdi_added:
            for c in sorted_cand:
                if c["type"] == "Shatabdi":
                    selected.append(c)
                    shatabdi_added = True
                    break

        pass_count = 0
        for c in sorted_cand:
            if c["type"] == "Passenger" and c not in selected and pass_count < 3:
                selected.append(c)
                pass_count += 1

        for c in sorted_cand:
            if len(selected) >= target_count:
                break
            if c["type"] == "Shatabdi":
                continue
            if c not in selected:
                selected.append(c)

        return selected

    selected_up = _select_trains(up_candidates, "Up")
    selected_dn = _select_trains(dn_candidates, "Down")

    day0_schedules: List[Tuple[TrainSchedule, bool]] = []
    for train_meta in selected_up:
        sched = _build_train_schedule(
            train_meta["train_number"],
            train_meta["train_name"],
            train_meta["type"],
            train_meta["rows"],
            stations,
            chainage_map,
            "Up",
        )
        if sched:
            day0_schedules.append((sched, train_meta["type"] == "Shatabdi"))

    for train_meta in selected_dn:
        sched = _build_train_schedule(
            train_meta["train_number"],
            train_meta["train_name"],
            train_meta["type"],
            train_meta["rows"],
            stations,
            chainage_map,
            "Down",
        )
        if sched:
            day0_schedules.append((sched, train_meta["type"] == "Shatabdi"))

    timetables = []
    for day in range(HORIZON_DAYS):
        day_offset = day * MINS_PER_DAY
        for sched, is_shatabdi in day0_schedules:
            if is_shatabdi and day == 2 and corridor_id == "SBC-JTJ":
                continue

            day_stops = [
                TrainStop(
                    station_id=stop.station_id,
                    arrival_mins=stop.arrival_mins + day_offset,
                    departure_mins=stop.departure_mins + day_offset,
                )
                for stop in sched.stops
            ]
            timetables.append(TrainSchedule(
                train_id=f"{sched.train_id}_D{day}",
                type=sched.type,
                direction=sched.direction,
                stops=day_stops,
            ))

    _cached_timetables[corridor_id] = timetables
    return timetables

# Backward-compatibility drop-in
CORRIDOR_STATIONS: List[Station] = get_corridor_stations("SBC-JTJ")
